language: node_js
node_js:
  - "12"
dist: trusty
branches:
  only:
    - master
    - develop
before_script:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run build -- --prod
deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN"
